#!/bin/bash
#SBATCH -N 1
#SBATCH -n 64
#SBATCH -J 6230-openmp
#SBATCH -t 00:30:00
#SBATCH -C amd

#TBB Settings:
export TBB_NUM_THREADS=64

#OpenMP settings:
export OMP_NUM_THREADS=64
export OMP_PLACES=cores

#run the application:
./test_code -n 100000
./test_code -n 200000
./test_code -n 400000
./test_code -n 800000
./test_code -n 1600000
./test_code -n 3200000
